# Generated by Django 4.0.1 on 2022-01-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CgGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('owner', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('picture', models.ImageField(
                    default='default.jpg', upload_to='profile_pics')),
                ('group', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeguru.cggroup')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(
                    default='0rRoE464lz4yiUSV67CkLzZFeEqQdi1olC6dhQDFlpvSeOtrYdGGj7KfQBboFGrV', max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='codeguru.cggroup')),
            ],
        ),
    ]
