# Generated by Django 4.0.1 on 2022-01-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='jD3gamZvyjGgaKwo2325ht1NCXTEzB4qouQLbSl7J6M0O1Jyl4NSvsgn7Q0WJgwp', max_length=64, unique=True),
        ),
    ]
