# Generated by Django 4.0.1 on 2022-01-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0002_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='AXV4sZYcmDdFkeC24idckyxtSumMGKPmKZf9xtfVPgfgLatxYBIi7Y4e7cgMHLBU', max_length=64, unique=True),
        ),
    ]
