# Generated by Django 4.0.2 on 2022-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0002_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='qfTYAqVT2tIKPr6M79fJbRHSw6BlF64UJFisaaBZMoktjmhuaUq7ABJJK1jdjFfM', max_length=64, unique=True),
        ),
    ]
