# Generated by Django 4.0.1 on 2022-01-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0003_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='2zAqjEmcHdh8h8wWNsFf7ltOrEsCANx1nj8z31wvazGOfom8GVxdcDjJFNDTtxxE', max_length=64, unique=True),
        ),
    ]
