# Generated by Django 4.0.1 on 2022-01-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0004_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='cFlw70phcjHWsIztxkTeIGaMBohgdt6WBIUzGYb5CepoczbDkau9GFnFsy5ewJ2D', max_length=64, unique=True),
        ),
    ]
