# Generated by Django 4.0.1 on 2022-01-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0005_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='gSuRw5uaQy7OCjg9iqdtqp2tzK9fWzVBdkT04oVfmDw1MGHDn6GXwesjqJNaJZ9h', max_length=64, unique=True),
        ),
    ]
