# Generated by Django 3.2.11 on 2022-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0006_alter_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cggroup',
            name='center',
            field=models.CharField(choices=[(
                'IND', 'Independent'), ('GSA', 'Green Start Academy')], default='IND', max_length=3),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='xlco7hiF736VjThXhTm9kEvDabHJOecHnvcvUktOAGkGDPKx3GZWyJQRdsBj1UKE', max_length=64, unique=True),
        ),
    ]
