# Generated by Django 3.2.11 on 2022-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0007_auto_20220123_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='SIb21rhsprDfWfHzGhSuWFiK00lhFN3NMXTvtyxFQisOdnKvPXVdK1i0K0RCU57Q', max_length=64, unique=True),
        ),
    ]
