# Generated by Django 3.2.11 on 2022-01-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0008_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='i3G7IuIAU1tpfLeh50EkHWczZH1uQ3kR8iBEY0e9cMf6OTkKmnNO634EfkJesCwn', max_length=64, unique=True),
        ),
    ]
