# Generated by Django 3.2.11 on 2022-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0009_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='wWXBuZqaISz3nju2xf5vbrurPlbXnIQ10O5b4cX0q1z8HIXPG4LflLhOkGTLzULw', max_length=64, unique=True),
        ),
    ]
