# Generated by Django 3.2.11 on 2022-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0010_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='RNWk6IL2UPLtMKwLU9J59ZrD7tbi5YodceyKnuft5VO6OvDhzgsqHnD9etyr5vYC', max_length=64, unique=True),
        ),
    ]
