# Generated by Django 3.2.11 on 2022-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0012_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='3TeqnodVzZeYk3q8IApj0QvnictsFxCHpy2FCfujVrfvdeL0CO5RPCpBgeirpDGX', max_length=64, unique=True),
        ),
    ]
