# Generated by Django 3.2.11 on 2022-01-24 19:04

import codeguru.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0013_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cggroup',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[
                                   codeguru.models.group_name_validator]),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='hOAsSdZG6xMkLEjPVAO6K0r1WBwpfeDQNK9FA1NQHe83aiWISCby5uQiknUo0yCt', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(
                default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
