# Generated by Django 3.2.11 on 2022-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0014_auto_20220124_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='JFS5W6FLNjptGdU63mgIFOT7qkipuIc1cPiViQqhkejtGRuq0tMXzPGQAASKSQm5', max_length=64, unique=True),
        ),
    ]
