# Generated by Django 3.2.11 on 2022-01-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0016_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='05QanekaWE0LPiEp1gSLtfaiI3Kyi1QVMxYUX7uV40y8P9ZI4kxiGWdCKJM9YIyq', max_length=64, unique=True),
        ),
    ]
