# Generated by Django 3.2.11 on 2022-01-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0017_alter_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='vxsi3bZ1KmszIIVWrreg59g39yjtK9eDrxZWPM6oMbCWcc2nzJGEfU0NF8X0qlKv', max_length=64, unique=True),
        ),
    ]
