# Generated by Django 3.2.11 on 2022-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0018_auto_20220128_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='Uvmr2euoESPmSYC1chXHF2vlTz95uQBkMiIq7P34CNiZ6oruZhN63wuDk8F6uZp6', max_length=64, unique=True),
        ),
    ]
