# Generated by Django 3.2.11 on 2022-01-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0019_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='issxCfHdDVA4NsPM8cyMidyeidwLMWbmyXrvH6kCYxlldWbkzAY0ITcgAgE1Otoq', max_length=64, unique=True),
        ),
    ]
