# Generated by Django 3.2.11 on 2022-01-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0020_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='lQh6B751zHcCIFUOI0iV2Ujn5qZ3TivSPiDF6MZfDblxUTz9VsPoU95RJbHAFOuQ', max_length=64, unique=True),
        ),
    ]
