# Generated by Django 3.2.11 on 2022-01-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0022_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(
                default='g79EcuHd6nMnwyX9tkYCX5wZbCsj64XkW1AJo6Tt5BB4KIiLEH67UTnc2NNnFzbo', max_length=64, unique=True),
        ),
    ]
