# Generated by Django 4.0.1 on 2022-01-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0023_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='rPGmEwqG7eROHbA0Iccob1T2lBhsFoFNT4mGFEO3dR4dcaWubkiOEhSYlX9Ejjz3', max_length=64, unique=True),
        ),
    ]
