# Generated by Django 4.0.1 on 2022-01-31 22:13

import codeguru.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0024_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cggroup',
            name='center',
            field=models.CharField(default='IND', max_length=3, validators=[codeguru.models.validate_center]),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='ykZE7Do1dMbHsLRU9hgolHfXjCTBwPg8DgSnkuhdW2cCVAqto0g8XFQAAPV8muUI', max_length=64, unique=True),
        ),
    ]
