# Generated by Django 4.0.1 on 2022-01-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0025_alter_cggroup_center_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='jRN4O40bEnKWP0d7RWGQKMaquNdb9MoTSjVE2dJtEAwYMeVHgUFwU3BN5336fBDF', max_length=64, unique=True),
        ),
    ]
