# Generated by Django 4.0.1 on 2022-01-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0027_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='Nhb2xgdt1wpbfNck3hG8rCIcMF7NFvepBdgdDkTMtUnj9wMO8vuEdsx1TQYSHai7', max_length=64, unique=True),
        ),
    ]
