# Generated by Django 4.0.1 on 2022-01-31 23:09

import codeguru.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeguru', '0028_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cggroup',
            name='center',
            field=models.CharField(default='IND', max_length=3, validators=[codeguru.models.validate_center], verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='cggroup',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[codeguru.models.group_name_validator], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='JazyZLBKRYpdlpcJbcIhlhsfq7DIf08coviD0yHNv8NBPW7qWg0gfHx8ztZKCEDS', max_length=64, unique=True),
        ),
    ]
