# Generated by Django 3.2.11 on 2022-01-23 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import war.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codeguru', '0011_alter_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount_of_survivors', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('zombie_mode', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm_file', models.FileField(upload_to=war.models.war_directory_path, validators=[war.models.asm_max])),
                ('bin_file', models.FileField(upload_to=war.models.war_directory_path, validators=[war.models.bin_max])),
                ('result', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru.cggroup')),
                ('war', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='war.war')),
            ],
        ),
        migrations.CreateModel(
            name='RiddleSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle_solution', models.FileField(upload_to=war.models.riddle_directory_path)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codeguru.cggroup')),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war.riddle')),
            ],
        ),
    ]
