# Generated by Django 3.2.11 on 2022-01-28 11:51

import django.core.files.storage
from django.db import migrations, models
import war.models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0002_riddlesolution_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlesolution',
            name='riddle_solution',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(
                location='/Users/idosharon/Documents/Projects/Coding_Projects/Codeguru_Extreme/codeguru-website/data'), upload_to=war.models.riddle_directory_path),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='asm_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(
                location='/Users/idosharon/Documents/Projects/Coding_Projects/Codeguru_Extreme/codeguru-website/data'), upload_to=war.models.asm_surv_upload, validators=[war.models.asm_max]),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='bin_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(
                location='/Users/idosharon/Documents/Projects/Coding_Projects/Codeguru_Extreme/codeguru-website/data'), upload_to=war.models.bin_surv_upload, validators=[war.models.bin_max]),
        ),
    ]
