# Generated by Django 3.2.11 on 2022-01-28 12:44

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import war.models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0003_auto_20220128_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='upload_date',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survivor',
            name='asm_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(
                location='/Users/idosharon/Documents/Projects/Coding_Projects/Codeguru_Extreme/codeguru-website/data'), upload_to=war.models.asm_surv_upload, validators=[war.models.asm_max]),
        ),
    ]
